### ISSUE TITLE
Handling of building blocks with few placer_ids

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#235] opened 2020-08-26 03:25 UTC
Throughout stk, many building block orientations rely on either:

- having at least 2 or 3 atoms that are placer ids for plane-based orientations
- having at least 2 or 3 atoms that are core-atoms and **not** placer ids

Some .Vertex classes require both, some require only one, but using a building block like:
`stk.BuildingBlock('BrCBr', [BromoFactory()])` is problematic because the placer_ids is len 1 and is == the core_ids. Therefore, any placer - core vector will be [0,0,0].

Not sure what the best way to handle this is... perhaps a check during vertex placement whether orientation is possible.

Furthermore, tests will need to be updated to handle this change.

**Comment by lukasturcani** [comment] 2020-08-26 07:20
I believe this is a duplicate of #156 ?

**Closed** 2020-09-16 12:46 UTC
