### ISSUE TITLE
pip install misses pywindow

### ISSUE THREAD

**Issue by richardjgowers** [lukasturcani/stk#92] opened 2020-01-15 11:50 UTC
I've done an install of stk (v 2019.10.21.0) via pip and on import I get `ModuleNotFoundError: No module named 'pywindow'`

**Comment by lukasturcani** [comment] 2020-01-15 11:53
Hi, This is probably caused by a missing requirement in the setup.py. If you run `pip install pywindowx` it should fix it I believe.

**Comment by lukasturcani** [comment] 2020-04-23 10:45
Fixed in #95

**Closed by lukasturcani** 2020-04-23 10:45 UTC
